### ISSUE TITLE
Missing $HOME/.config/polybar/system

### ISSUE THREAD

**Issue by tiaguinho-code** [heapbytes/dotfiles#3]
Hey, I might be overlooking something but it seems like the .config/polybar/system directory is missing in the dotfiles.

**Comment by heapbytes** [comment]
Heyy, could you please give me an screenshot (which part of polybar isn't working) or give a brief about the issue so i can update the dotfiles as per it.

**Comment by heapbytes** [comment]
Hello, thanks for bringing it up, i have updated the dotfiles.
