### ISSUE TITLE
Some other possible issues

### ISSUE THREAD

**Issue by tiaguinho-code** [heapbytes/dotfiles#4]
Thanks for the swift response and fix on the other issue :)

I found some other possible issues:

- The launch.sh might be missing from the .config/polybar
- maybe you could mention in the readme that xorg-xsetroot is a dependency (I didnt have it installed and am still trying to get everything to work)
- I'm not sure what rofi_run in sxhkd is but if it's custom it doesn't seem to be included in the repo
- I didn't find the way the background should be set. Should this just go by feh or how is it supposed to work?
- The font dependencies would be nice to have in the readme aswell 

I'm sorry if there are any obvious noob mistakes in these questions/issues and look forward to your response/fix

**Comment by heapbytes** [comment]
I see, 
1) I use the same launch.sh that i have in my `old-polybar` folder (with very less changes)
2) xorg-xsetroot is the base package that every arch linux user installs, so i didn't think it's that imp.
3) yes rofi_run was a old config i used, i don't use it anymore and the shortcuts of it are used for other task. (sxhkd file is just for my backup tbh :joy: )
4) yes you can use feh to set the background.
5) most of the terminal fonts was installed by `powelevel10k` which is a dependency in the readme (tho i'll add some now)

no problem, i am always happy to help, for any further info you can contact me through discord (lenon#6176)
i will keep open this issue for a while (or you can close it)
