### ISSUE TITLE
This is insane

### ISSUE THREAD

**Issue by JoshuaDRose** [heapbytes/dotfiles#5]
Hey, this isn't really a bug or anything like that but I just wanted to say that this is a huge inspiration for me. I'm working on a lot of changes right now and this was a huge motivating factor that really helped me improve the aesthetic of my workflow

**Comment by heapbytes** [comment]
haha thanks :heart:  
have you tried my distro <a href="https://github.com/vitunix"> Vitunix </a> yet ?
it comes with bspwm (for now) and have a nerdy rice. More info our <a href="https://vitunix.github.io"> website</a>.
