### ISSUE TITLE
Add the full list of dependecies and fix the polybar config file

### ISSUE THREAD

**Issue by 96jaco96** [heapbytes/dotfiles#6]
Hello, this is a suggestion/enhancement and bug fix request.

First the suggestion: 

edit the README to include the FULL list of dependencies;
especially ALL the extensions for polybar and the xorg dependecies.

If someone (like me) start from a clean minimal Arch Linux installation i don't have neither xorg nor the packages to make the cool stuff in polybar work (battery, temperature, now playing etc...)

secondarly the bug fixes:

Polybar config file has some issues;

- first of all there are unscaped backslashes that need to be escaped with another backslash (for example "google\-mdi:size=12;3" in line 58
- secondarly the Launch.sh is not working properly. And the error that it throws is: "The config file contains multiple bars, but no bar name was given" 

And lastly, as a personal note:

I saw your Linux distro Vitunix and i like that! It's a great idea to ship an already somewhat clean and riced Arch installation BUT while keeping it minimal as Arch should be! 
I thought that it would be extremely nice if that distro shipped with this rice of this repo! It's probably the best, most balanced, all around ricing that i've seen! 
Shipping it with a minimal Arch distro would make it so much appealing to people that are searching just that!

**Comment by heapbytes** [comment]
Heyy, you can create a fork and do the changes you feel is important (i will surely review it and merge), sorry right now i am busy with my exams and some other pending projects, 
btw for the xorg, I installed all the packages so i am not aware of exact packages the rice is using, and yeah for vitunix i choose to keep it decent rice, may update new rice on next release, (though you can use this configs on vitunix and make it look exact same way) .

**Comment by 96jaco96** [comment]
Alright i'll do just that ^~^ 
Maybe later next week since i'm kinda busy too...
Good luck with your exams and thanks :)

**Comment by amplexus** [comment]
Hey this rice looks awesome! Kudos to you @heapbytes.

I think as well the `.config/bspwm/bpswmrc` file refers to a `.config/polybar/launch.sh` script that doesn't exist - though it does exist under `.config/old-polybar`.

And the only other problem I saw/experienced was under the nvim config where `.config/nvim/lua/plugins/init.lua` pulls down the NvChad/base46 plugin. I got an error that the `load_theme` function doesn't exist. 

The cause of this is that the base46 plugin git repo now defaults to the "2.0" branch. You need to explicitly specify the 'master' branch for that plugin, which will get rid of the error.

I'm still trying to get this rice working on my Kubuntu 22.10 laptop. If I do manage to iron out all the issues I'm experiencing I'll submit a PR. I'm new to bspwm + polybar + all the other goodies here so it may be a while...

**Comment by charan-nunnabhatla** [comment]
> Hello, this is a suggestion/enhancement and bug fix request.
> 
> First the suggestion: 
> 
> edit the README to include the FULL list of dependencies;
> especially ALL the extensions for polybar and the xorg dependecies.
> 
> If someone (like me) start from a clean minimal Arch Linux installation i don't have neither xorg nor the packages to make the cool stuff in polybar work (battery, temperature, now playing etc...)
> 
> secondarly the bug fixes:
> 
> Polybar config file has some issues;
> 
> - first of all there are unscaped backslashes that need to be escaped with another backslash (for example "google\-mdi:size=12;3" in line 58
> - secondarly the Launch.sh is not working properly. And the error that it throws is: "The config file contains multiple bars, but no bar name was given" 
> 
> And lastly, as a personal note:
> 
> I saw your Linux distro Vitunix and i like that! It's a great idea to ship an already somewhat clean and riced Arch installation BUT while keeping it minimal as Arch should be! 
> I thought that it would be extremely nice if that distro shipped with this rice of this repo! It's probably the best, most balanced, all around ricing that i've seen! 
> Shipping it with a minimal Arch distro would make it so much appealing to people that are searching just that! 

Hey..
"The config file contains multiple bars, but no bar name was given" did this be solved?

**Comment by heapbytes** [comment]
> > Hello, this is a suggestion/enhancement and bug fix request.
> > 
> > First the suggestion: 
> > 
> > edit the README to include the FULL list of dependencies;
> > especially ALL the extensions for polybar and the xorg dependecies.
> > 
> > If someone (like me) start from a clean minimal Arch Linux installation i don't have neither xorg nor the packages to make the cool stuff in polybar work (battery, temperature, now playing etc...)
> > 
> > secondarly the bug fixes:
> > 
> > Polybar config file has some issues;
> > 
> > - first of all there are unscaped backslashes that need to be escaped with another backslash (for example "google\-mdi:size=12;3" in line 58
> > - secondarly the Launch.sh is not working properly. And the error that it throws is: "The config file contains multiple bars, but no bar name was given" 
> > 
> > And lastly, as a personal note:
> > 
> > I saw your Linux distro Vitunix and i like that! It's a great idea to ship an already somewhat clean and riced Arch installation BUT while keeping it minimal as Arch should be! 
> > I thought that it would be extremely nice if that distro shipped with this rice of this repo! It's probably the best, most balanced, all around ricing that i've seen! 
> > Shipping it with a minimal Arch distro would make it so much appealing to people that are searching just that! 
> 
> Hey..
> "The config file contains multiple bars, but no bar name was given" did this be solved? 



Yeah bro almost polybar has many bars, here use the main one...

**Comment by heapbytes** [comment]
> Hey this rice looks awesome! Kudos to you @heapbytes.
> 
> 
> 
> I think as well the `.config/bspwm/bpswmrc` file refers to a `.config/polybar/launch.sh` script that doesn't exist - though it does exist under `.config/old-polybar`.
> 
> 
> 
> And the only other problem I saw/experienced was under the nvim config where `.config/nvim/lua/plugins/init.lua` pulls down the NvChad/base46 plugin. I got an error that the `load_theme` function doesn't exist. 
> 
> 
> 
> The cause of this is that the base46 plugin git repo now defaults to the "2.0" branch which appears to have deprecated that function. You need to explicitly specify the 'master' branch for that plugin in `.config/nvim/lua/plugins/init.lua`, which will get rid of the error.
> 
> 
> 
> I'm still trying to get this rice working on my Kubuntu 22.10 laptop. If I do manage to iron out all the issues I'm experiencing I'll submit a PR. I'm new to bspwm + polybar + all the other goodies here so it may be a while...

Thanks, I'll be waiting for the pr, the main issue is I don't use this  polybar anymore, this week I'll solve it by installing it again 🙌

**Comment by heapbytes** [comment]
https://github.com/gh0stzk/dotfiles/tree/master/config/bspwm/rices/pamela
here,
i found the repo of the base polybar, there wont be few features like github stats cuz i edited that later.
