### ISSUE TITLE
Add which picom fork to use?

### ISSUE THREAD

**Issue by vinivosh** [heapbytes/dotfiles#9]
First of all, thanks for this beautiful eye-candy! Really nice.

Now, I don't know if I'm missing something, but which exact Picom fork do you use with this? [ibhagwan's](https://github.com/ibhagwan/picom)? Seems to be what's mentioned in the blur setion of [`picom.conf`](https://github.com/heapbytes/dotfiles/blob/main/.config/picom/picom.conf), but I wanted to be absolutely sure before messing around with these.

**Comment by heapbytes** [comment]
yehp you are correct, it's ibhagwan's fork.
